# Generated by Django 6.0.7 on 2026-07-18 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=30)),
                ('reason_code', models.CharField(choices=[('MISSING_IN_SYSTEM_A', 'Record exists in System B but not in System A'), ('MISSING_IN_SYSTEM_B', 'Record exists in System A but not in System B'), ('INVALID_SYSTEM_A_RECORD_ID', 'System A record identifier is missing or invalid'), ('MISSING_SYSTEM_B_REFERENCE', 'System B entry has no record reference'), ('INVALID_SYSTEM_B_REFERENCE', 'System B record reference is invalid'), ('UNRESOLVED_SYSTEM_B_REFERENCE', 'System B reference cannot be matched to a System A record'), ('MISSING_SYSTEM_A_LOCATION', 'System A has no location for this record'), ('MISSING_SYSTEM_B_LOCATION', 'System B has no location for this record'), ('UNKNOWN_SYSTEM_A_LOCATION', 'System A location is not present in the location mapping'), ('UNKNOWN_SYSTEM_B_LOCATION', 'System B location is not present in the location mapping'), ('LOCATION_MISMATCH', 'System A and System B recorded different locations'), ('TENANT_MISMATCH', 'System A and System B records belong to different organizations'), ('MISSING_SYSTEM_A_DATE', 'System A has no event date for this record'), ('MISSING_SYSTEM_B_DATE', 'System B has no recorded date for this record'), ('INVALID_SYSTEM_A_DATE', 'System A event date could not be parsed'), ('INVALID_SYSTEM_B_DATE', 'System B recorded date could not be parsed'), ('DATE_MISMATCH', 'System A and System B recorded different dates'), ('MISSING_SYSTEM_A_VALUE', 'System A has no total value for this record'), ('MISSING_SYSTEM_B_VALUE', 'System B has no value for this record'), ('INVALID_SYSTEM_A_VALUE', 'System A total value could not be parsed'), ('INVALID_SYSTEM_B_VALUE', 'System B value could not be parsed'), ('VALUE_MISMATCH', 'System A and System B recorded different total values'), ('DUPLICATE_SYSTEM_B_ENTRY', 'System B contains duplicate entries for this record'), ('AMBIGUOUS_SYSTEM_B_ENTRIES', 'Multiple System B entries exist and cannot be safely reconciled')], max_length=50)),
                ('reason', models.CharField(max_length=255)),
                ('system_a_record_id', models.CharField(blank=True, max_length=30)),
                ('system_b_entry_ids', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='tenants.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='tenants.organization')),
            ],
            options={
                'ordering': ('record_id', 'reason_code'),
                'indexes': [models.Index(fields=['organization', 'reason_code'], name='reconciliat_organiz_ed26f1_idx'), models.Index(fields=['organization', 'location'], name='reconciliat_organiz_8733e1_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'record_id', 'reason_code'), name='unique_exception_per_org_record_reason')],
            },
        ),
    ]
