# Generated by Django 6.0.7 on 2026-07-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    RLS_SQL = """
        ALTER TABLE reconciliation_reconciliationexception
        ENABLE ROW LEVEL SECURITY;

        ALTER TABLE reconciliation_reconciliationexception
        FORCE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS reconciliation_exception_org_isolation
        ON reconciliation_reconciliationexception;

        CREATE POLICY reconciliation_exception_org_isolation
        ON reconciliation_reconciliationexception
        FOR ALL
        TO USERADMIN
        USING (
            organization_id = NULLIF(
            current_setting('app.current_org_id', true),
            ''
            )::bigint
        )      
        WITH CHECK (
            organization_id = NULLIF(
            current_setting('app.current_org_id', true),
            ''
            )::bigint
        );
    """
    REVERSE_RLS_SQL = """
        DROP POLICY IF EXISTS reconciliation_exception_org_isolation
        ON reconciliation_reconciliationexception;

        ALTER TABLE reconciliation_reconciliationexception
        NO FORCE ROW LEVEL SECURITY;

        ALTER TABLE reconciliation_reconciliationexception
        DISABLE ROW LEVEL SECURITY;
    """
    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=RLS_SQL,
            reverse_sql=REVERSE_RLS_SQL,
        )
    ]
